#!/usr/bin/env python

from pathlib import Path
import yaml

def generate_tests():
    Path.mkdir(Path("events/test"), exist_ok=True)
    with Path("events/test/test.md").open("w") as file:
        file.write("""---
layout: sessions
title: Test
event: test
list: true
redirect_from:
- /events/test
- /web/sessions/test
- /web/sessions/*/test
---""")
    print("Test event generated")
    Path.mkdir(Path("web/sessions/test"), exist_ok=True)
    Path.mkdir(Path("web/sessions/test/test"), exist_ok=True)
    with Path("web/sessions/test/test/session-1.md").open("w") as file:
        file.write("""---
layout: sessions
event: test
id: 0
title: >
    Test
---""")
    print("Test session generated")


generate_tests()
